worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    server_tokens off;
    # Variable-based proxy_pass needs Docker's embedded DNS resolver.
    resolver 127.0.0.11 valid=30s ipv6=off;
    resolver_timeout 5s;

    map $host $lab_upstream {
        default                     http://www:80;
        corp-demo.test              http://www:80;
        www.corp-demo.test          http://www:80;
        api.corp-demo.test          http://api:80;
        admin.corp-demo.test        http://admin:80;
        dev.corp-demo.test          http://dev:80;
        docs.corp-demo.test         http://docs:80;
        jenkins.corp-demo.test      http://jenkins:80;
        manager.corp-demo.test      http://manager:80;
        console.corp-demo.test      http://console:80;
        sso.corp-demo.test          http://sso:80;
        secure.corp-demo.test       http://sso:80;
        status.corp-demo.test       http://docs:80;
        vpn-gw.corp-demo.test       http://sso:80;
        search.corp-demo.test       http://intel:80;
        intel.corp-demo.test        http://intel:80;
    }

    server {
        listen 80 default_server;
        listen 443 ssl default_server;
        server_name _;

        ssl_certificate     /etc/nginx/certs/lab.crt;
        ssl_certificate_key /etc/nginx/certs/lab.key;

        location / {
            proxy_pass $lab_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
