graph TD;
  ASSET["资产"];
  ANALYSIS["资产分析"];
  TAG["资产标签"];
  REL_CLASSIFY{"分类"};
  REL_MARK{"标注"};

  ASSET -->|1| REL_CLASSIFY;
  REL_CLASSIFY -->|1| ANALYSIS;
  ASSET -->|1| REL_MARK;
  REL_MARK -->|N| TAG;

  A1(["资产id"]) --- ASSET;
  A2(["域名"]) --- ASSET;
  A3(["IP地址"]) --- ASSET;
  A4(["端口"]) --- ASSET;
  A5(["状态码"]) --- ASSET;
  A6(["标题"]) --- ASSET;
  A7(["服务"]) --- ASSET;
  A8(["首次发现时间"]) --- ASSET;
  A9(["最近发现时间"]) --- ASSET;

  B1(["分析id"]) --- ANALYSIS;
  B2(["资产id"]) --- ANALYSIS;
  B3(["资产类型"]) --- ANALYSIS;
  B4(["模型置信度"]) --- ANALYSIS;
  B5(["分析时间"]) --- ANALYSIS;

  C1(["标签id"]) --- TAG;
  C2(["资产id"]) --- TAG;
  C3(["标签名称"]) --- TAG;
  C4(["标签来源"]) --- TAG;
  C5(["置信度"]) --- TAG;
  C6(["命中规则"]) --- TAG;
  C7(["创建时间"]) --- TAG;
